create table microdados2021
(
	Codigo_da_Matricula int primary key,
	Carga_Horaria int,
	Carga_Horaria_Minima int,
	Categoria_da_Situacao varchar(50),
	Co_Inst int,
	Cod_Unidade int,
	Cor__Raca varchar(20),	
	Codigo_da_Unidade_de_Ensino__SISTEC int,
	Codigo_do_Ciclo_Matricula int,
	Codigo_do_Municipio_com_DV int,
	Data_de_Fim_Previsto_do_Ciclo date,
	Data_de_Inicio_do_Ciclo date,
	Data_de_Ocorrencia_da_Matricula date,
	Eixo_Tecnologico varchar(100),
	Faixa_Etaria varchar(20),
	Fator_Esforco_Curso varchar(10),
	Fonte_de_Financiamento varchar(30),
	Idade int,
	Instituicao varchar(60),
	Matriculas_Atendida varchar(10),
	Matriculas_Equivalentes varchar(10),
	Modalidade_de_Ensino varchar(60),
	Municipio varchar(60),
	Mes_De_Ocorrencia_da_Situacao varchar(20),
	Nome_de_Curso varchar(100),
	Numero_de_registros int,
	Regiao varchar(20),
	Renda_Familiar varchar(20),
	Sexo varchar(10),
	Situacao_de_Matricula varchar(20),
	Subeixo_Tecnologico varchar(60),
	Tipo_de_Curso varchar(60),
	Tipo_de_Oferta varchar(60),
	Total_de_Inscritos int,
	Turno varchar(20),
	UF char(2),
	Unidade_de_Ensino varchar(100),
	Vagas_Ofertadas int
);